<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="25" hostname="MCKL-20005142" name="restassuredapi.test.FetchUserDetails" tests="27" failures="0" timestamp="08 Feb 2022 11:00:22 GMT" time="1.578" errors="2">
  <testcase name="A_05_Test_InvalidIdValue" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_05_Test_InvalidIdValue -->
  <testcase name="A_07_Test_InvalidSubUser" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_07_Test_InvalidSubUser -->
  <testcase name="A_05_Test_InvalidIdValue" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_05_Test_InvalidIdValue -->
  <testcase name="A_07_Test_InvalidSubUser" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_07_Test_InvalidSubUser -->
  <testcase name="A_07_Test_InvalidSubUser" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_07_Test_InvalidSubUser -->
  <testcase name="A_04_Test_idType_Invalid" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_04_Test_idType_Invalid -->
  <testcase name="A_07_Test_InvalidSubUser" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_07_Test_InvalidSubUser -->
  <testcase name="A_04_Test_idType_Invalid" time="0.003" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_04_Test_idType_Invalid -->
  <testcase name="A_09_Test_UserStatusIsResumed" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_09_Test_UserStatusIsResumed -->
  <testcase name="A_01_Test_Success_LoginId" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_01_Test_Success_LoginId -->
  <testcase name="A_07_Test_InvalidSubUser" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_07_Test_InvalidSubUser -->
  <testcase name="A_09_Test_UserStatusIsResumed" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_09_Test_UserStatusIsResumed -->
  <testcase name="A_04_Test_idType_Invalid" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_04_Test_idType_Invalid -->
  <testcase name="A_09_Test_UserStatusIsResumed" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_09_Test_UserStatusIsResumed -->
  <testcase name="setupReporter" time="1.557" classname="restassuredapi.test.FetchUserDetails">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
at com.utils._masterVO.loadWebTestCases(_masterVO.java:432)
at com.utils._masterVO.loadVO(_masterVO.java:66)
at com.classes.BaseTest.setupReporter(BaseTest.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setupReporter -->
  <testcase name="A_09_Test_UserStatusIsResumed" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_09_Test_UserStatusIsResumed -->
  <testcase name="A_01_Test_Success_LoginId" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_01_Test_Success_LoginId -->
  <testcase name="A_05_Test_InvalidIdValue" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_05_Test_InvalidIdValue -->
  <testcase name="A_01_Test_Success_LoginId" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_01_Test_Success_LoginId -->
  <testcase name="A_04_Test_idType_Invalid" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_04_Test_idType_Invalid -->
  <testcase name="A_04_Test_idType_Invalid" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_04_Test_idType_Invalid -->
  <testcase name="A_05_Test_InvalidIdValue" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_05_Test_InvalidIdValue -->
  <testcase name="tearDown" time="0.002" classname="restassuredapi.test.FetchUserDetails">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.classes.BaseTest.tearDown(BaseTest.java:117)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="A_09_Test_UserStatusIsResumed" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_09_Test_UserStatusIsResumed -->
  <testcase name="A_01_Test_Success_LoginId" time="0.001" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_01_Test_Success_LoginId -->
  <testcase name="A_01_Test_Success_LoginId" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_01_Test_Success_LoginId -->
  <testcase name="A_05_Test_InvalidIdValue" time="0.000" classname="restassuredapi.test.FetchUserDetails">
    <skipped/>
  </testcase> <!-- A_05_Test_InvalidIdValue -->
</testsuite> <!-- restassuredapi.test.FetchUserDetails -->
